# Generated by Django 6.0 on 2026-01-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='website',
            new_name='website_url',
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='website_label',
            field=models.CharField(default='Visit Website', max_length=100),
        ),
    ]
