# Generated by Django 6.0 on 2026-01-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_website_client_website_url_client_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='description',
        ),
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='description_heading',
            field=models.CharField(default='Project Description', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='website_label',
            field=models.CharField(default='Visit Website', max_length=50),
        ),
    ]
