# Generated by Django 6.0 on 2026-01-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_description_alter_client_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description_heading',
            field=models.CharField(default='Project Description', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/logos/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='website_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
